# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/$(src)/../../../include

ifneq ($(filter m y,$(CONFIG_USE_MMI_CHARGER)),)
	EXTRA_CFLAGS += -DUSE_MMI_CHARGER
	EXTRA_CFLAGS += -I$(srctree)/$(src)/../../../drivers/power/mmi_charger
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../mmi_charger/$(GKI_OBJ_MODULE_DIR)/Module.symvers
endif

ifneq ($(filter m y, $(ADAPTIVE_TOLERANCE_OPTIMIZATION)),)
	EXTRA_CFLAGS += -DADAPTIVE_TOLERANCE_OPTIMIZATION
endif

obj-$(CONFIG_MOTO_FOGOS_MODULES) += qpnp_adaptive_charge.o
