# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/$(src)/../../include

obj-$(CONFIG_MOTO_FOGOS_MODULES) += moto_mm.o

moto_mm-y := mm_main.o mm_sysfs.o mm_info.o mm_lru_shrinker.o

