# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/$(src)/../../include

mmi_info-objs += mmi_storage_info.o
mmi_info-objs += mmi_ram_info.o
mmi_info-objs += mmi_unit_info.o
mmi_info-objs += mmi_boot_info.o
mmi_info-objs += mmi_info_main.o
obj-$(CONFIG_MOTO_FOGOS_MODULES) += mmi_info.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../mmi_annotate/$(GKI_OBJ_MODULE_DIR)/Module.symvers
