# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

obj-$(CONFIG_MOTO_FOGOS_MODULES) += mmi-smbcharger-iio/
obj-$(CONFIG_MOTO_FOGOS_MODULES) += qpnp_adaptive_charge/

