# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/$(src)/../../include

moto_f_usbnet-objs += f_usbnet.o
obj-$(CONFIG_MOTO_FOGOS_MODULES) += moto_f_usbnet.o
